[tool.poetry]
name = "zhvocab"
version = "0.1.0"
description = ""
authors = ["patarapolw <patarapolw@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
peewee = "^3.7"
wordfreq = "^2.2"
jieba = "^0.39.0"

[tool.poetry.dev-dependencies]
zhlib = {path = "../zhlib"}
